table Dax_Measures
	lineageTag: 1e6d6b7e-e86e-4c08-aa75-c434490c8b25

	measure Measure
		lineageTag: 0fb195c4-1d98-4ebe-adbd-69f53cf7bb5c

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure Show_Seller_Data =
			
			IF(
			    ISFILTERED('gold dim_seller'[seller_id]),
			    1,
			    0
			)
		formatString: 0
		lineageTag: 0bdffdba-6e1c-43dd-baa5-c7c73bdf3e63

	measure Login_Msg =
			
			VAR SellerID =
			    MAX('gold dim_seller'[seller_id])
			
			VAR SellerName =
			    CALCULATE(
			        MAX('gold dim_seller'[name]),
			        REMOVEFILTERS('gold dim_seller'),
			        'gold dim_seller'[seller_id] = SellerID
			    )
			RETURN
			IF(
			    ISFILTERED('gold dim_seller'[seller_id]),
			     "Welcome, " & SellerName & " 👋",
			   "Enter Your ID to View Your Dashboard"
			)
		lineageTag: ac4d78d5-8b2d-4ac7-90c0-c5c6fc44bd8f

	column Dummy
		formatString: 0
		lineageTag: 985a4668-6a06-4245-8a4d-f391d9ff0fe2
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Dummy]

		annotation SummarizationSetBy = Automatic

	partition Dax_Measures = calculated
		mode: import
		source =
				
				DATATABLE(
				    "Dummy", INTEGER,
				    { { 1 } }
				)

	annotation PBI_Id = 3bd0cd8633b043aeb8ed1ed516417eb6

