table 'gold dim_customer'
	lineageTag: b8705a0e-a0f7-4661-bd31-94903c5c4e74

	measure 'Total Revenue' = SUM('gold fact_sales'[gross_revenue])
		lineageTag: 6d1ad15d-2424-4017-aef6-40fa075e3e86

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Orders' = DISTINCTCOUNT('gold fact_sales'[order_id])
		formatString: 0
		lineageTag: 843bb4fa-4d82-4cf5-90c9-4f90574aa56e

	column customer_key
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		lineageTag: db8217aa-1c0d-451e-a682-a29b2bc51e90
		summarizeBy: none
		sourceColumn: customer_key

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		isNullable: false
		sourceProviderType: varchar(50)
		lineageTag: 6f98538e-76e5-4646-9397-c93d884beef1
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column location_key
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		lineageTag: 5c79acad-dc52-41db-87dd-51cab4b0a653
		summarizeBy: sum
		sourceColumn: location_key

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		sourceProviderType: nvarchar(150)
		lineageTag: 65dc403e-547d-4654-ba9a-7f854603d889
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		sourceProviderType: varchar(150)
		lineageTag: ebfdfc79-e871-4976-927d-53be3096b838
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		sourceProviderType: varchar(30)
		lineageTag: c22fecd9-8d5f-449d-aad2-88711497b921
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		sourceProviderType: varchar(20)
		lineageTag: 030e5316-01fc-48ca-b5ec-be2f2e22e7b7
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column age_band
		dataType: string
		sourceProviderType: varchar(20)
		lineageTag: 9e20660f-2ec4-43ca-a4fc-7b4e3af9283e
		summarizeBy: none
		sourceColumn: age_band

		annotation SummarizationSetBy = Automatic

	column registration_date
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 4334afb6-934a-47e8-a12b-89d2cfaa5da3
		summarizeBy: none
		sourceColumn: registration_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column is_current
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: tinyint
		lineageTag: fd58d6c8-543a-4e9b-ac00-0618aebd86ea
		summarizeBy: sum
		sourceColumn: is_current

		annotation SummarizationSetBy = Automatic

	column effective_from
		dataType: dateTime
		isNullable: false
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 9c2d1390-b747-4bb3-a531-90df4417da40
		summarizeBy: none
		sourceColumn: effective_from

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column effective_to
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: a208a506-b9bf-4a77-9b25-797cb62a3863
		summarizeBy: none
		sourceColumn: effective_to

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'gold dim_customer' = m
		mode: directQuery
		source =
				let
				    Source = Sql.Databases("tijartik-sql-server.database.windows.net"),
				    tijartek_reporting = Source{[Name="tijartek_reporting"]}[Data],
				    gold_dim_customer = tijartek_reporting{[Schema="gold",Item="dim_customer"]}[Data]
				in
				    gold_dim_customer

	annotation PBI_ResultType = Table

